title: Rats of NYC
email: chriskevinandrade@gmail.com
description: A data blog about the furry natives of New York City
author: PIT-DSC Rats Team
baseurl: ""
url: "https://rats.github.io"

# Social Profiles
twitter_username:
github_username: marmar897/RatsData
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
